package(default_visibility = ["//src/web/tasks_app:__subpackages__"])

filegroup(
  name = "client",
  srcs = [
    "index.html",
    "index.css",
    "request_utils.js",
    "simple_text_form.jsx",
    "navbar.jsx",
    "index_body.jsx",
  ]
)
